### ISSUE TITLE
Use datapack checker tool automatically

### ISSUE THREAD

**Issue by JollyChristopher** [JollyChristopher/JollyPacks#10]
I think all of the minor things in Ore Exchange will be compatible with other packs, but not sure for other packs I make. Might as well get it set up now.

**Comment by halemaster** [comment]
The way that works is kind of weird, going to see about making another or something based upon: https://mc-datapacks.github.io/en/index.html

**Comment by halemaster** [comment]
Definitely want to use the above, maybe instead have some checklist that marks off each when they are done.

- [ ] let's see what the checkmark does
